version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tenderblock_root_password
      MYSQL_DATABASE: tenderblockdb
    ports:
      - 3306:3306
